[repository]
name = "Lattice Official"
description = "Official Lattice package repository"

[packages.drivers_core]
monitor = { path = "drivers/core/monitor.lua", sha256 = "bb911926596f2984d0f0ef847df5cba75344d954fb5f38a1a66a812ed2303951" }
speaker = { path = "drivers/core/speaker.lua", sha256 = "0245a45b21035a3c1053f39fbc887fca7d1b2ca39fe772b799226f1e25d2703c" }

[packages.shared]
downloader = { path = "shared/downloader.lua", sha256 = "07f7158f6e8c7d09b937264b445328cda26e4e72b5c240e74d7d7fe0d67c8083" }
hardware_surveyor = { path = "shared/hardware_surveyor.lua", sha256 = "38d9b798f6a2aae9b935fed171e939e210ceafd86a3b4d89e22c285603a4c7af" }
log = { path = "shared/log.lua", sha256 = "32931972905b1dd71161db0d5da40fde41961085158e3305f32f046510e63fdc" }
nanoid = { path = "shared/nanoid.lua", sha256 = "2641bfaf9e80b1d6dbc0d79431d21663d10904cd3fe0ba606245b31d0c4e42c9" }
sha2 = { path = "shared/sha2.lua", sha256 = "1efccd26c9c423c13143b51c8aa3cd5ae436c0560fe87a04754eca22b1090942" }
toml = { path = "shared/toml.lua", sha256 = "689d43c7ef7056b96c5542bf59545700631c8d52b191f62437b364bb1832fe68" }

[packages.boot]
hardware_surveyor = { path = "boot/hardware_surveyor.lua", sha256 = "e008643bdfea273ea1ecd3658edabe3c5a7e9625dd00f1f6fa7e525ff2a3a3eb" }
lboot = { path = "boot/lboot.lua", sha256 = "b8cceb9e6548445e28ee744d7c3881ad141a25fcbf49fdb92ce848e91250925c" }
startup = { path = "boot/startup.lua", sha256 = "d7ab8552dadbbcbeb61bbc7e0cef67c3bb7a2396f894a5672a9cf54a8e22be94" }

[packages.kernel]
device_manager = { path = "kernel/device_manager.lua", sha256 = "aaab917f8db7e0a8d7d4aadc5a46373736ed0d6cddc778f0f6e93c33d5f8d20f" }
driver_registry = { path = "kernel/driver_registry.lua", sha256 = "d6340e7feaeabf53f93b599c1e4c5be46bdcd7aff0ba08309799570a22c75434" }
init = { path = "kernel/init.lua", sha256 = "4a01751c23c4a24349060e0f2fe35939c52ded9110cb7f7cf6ab7f003be57300" }

[packages.services]
audio = { path = "services/audio.lua", sha256 = "4c4897c91e7def021646ed3fa4f15718f9ef1c2857f612bbb401fc8eca7226e3" }
debug = { path = "services/debug.lua", sha256 = "13dd3d3bd2a25ae88d54e5443dc16c21c54d84a724d67830b3b91ada1b687925" }

[packages.config]

