[repository]
name = "Lattice Official"
description = "Official Lattice package repository"

[packages.drivers_core]
speaker = { path = "drivers/core/speaker.lua", sha256 = "0245a45b21035a3c1053f39fbc887fca7d1b2ca39fe772b799226f1e25d2703c" }

[packages.shared]
downloader = { path = "shared/downloader.lua", sha256 = "dfe1938746d80be1588372836b451033cb643f7b45e6b2daf2239870c787e16e" }
hardware_surveyor = { path = "shared/hardware_surveyor.lua", sha256 = "38d9b798f6a2aae9b935fed171e939e210ceafd86a3b4d89e22c285603a4c7af" }
log = { path = "shared/log.lua", sha256 = "32931972905b1dd71161db0d5da40fde41961085158e3305f32f046510e63fdc" }
nanoid = { path = "shared/nanoid.lua", sha256 = "1ac838d8286d0285879d39b2f870053091e689183440bbd8c4a57700059414fc" }
sha2 = { path = "shared/sha2.lua", sha256 = "1efccd26c9c423c13143b51c8aa3cd5ae436c0560fe87a04754eca22b1090942" }
toml = { path = "shared/toml.lua", sha256 = "689d43c7ef7056b96c5542bf59545700631c8d52b191f62437b364bb1832fe68" }

[packages.boot]
hardware_surveyor = { path = "boot/hardware_surveyor.lua", sha256 = "e008643bdfea273ea1ecd3658edabe3c5a7e9625dd00f1f6fa7e525ff2a3a3eb" }
lboot = { path = "boot/lboot.lua", sha256 = "b8cceb9e6548445e28ee744d7c3881ad141a25fcbf49fdb92ce848e91250925c" }
startup = { path = "boot/startup.lua", sha256 = "d7ab8552dadbbcbeb61bbc7e0cef67c3bb7a2396f894a5672a9cf54a8e22be94" }

[packages.kernel]
device_manager = { path = "kernel/device_manager.lua", sha256 = "0f16010534e2d37927520ba21e39b47504602631bfae616e0defc7d1f53cf29d" }
driver_registry = { path = "kernel/driver_registry.lua", sha256 = "d6340e7feaeabf53f93b599c1e4c5be46bdcd7aff0ba08309799570a22c75434" }
init = { path = "kernel/init.lua", sha256 = "fec482bc894bf211863a19918e05496d01de1d409a5aa5386d9d0fa93952e83d" }

[packages.services]
audio = { path = "services/audio.lua", sha256 = "b976739e3ba440faf28e8cb7b9410b9d2ca637d19db9f48521674d53c6f80f40" }

[packages.config]

