[system]
name = "Lattice"
version = "0.1.0"
codename = "Scaffold"

[node]
role = "controller"

[updates]
enabled = true
# Interval in seconds between update checks
interval = 86400 # 24 hours

[services.debug]
enabled = true

# [services.]
